extends: airbnb-base
plugins:
  - import
rules:
  no-process-env: 2
  no-underscore-dangle: off
globals:
  process: on
  describe: on
  before: on
  after: on
  beforeEach: on
  afterEach: on
  suite: on
  test: on
  it: on
  expect: on
